export const PACKAGENAME_INIT = 'PACKAGENAME_INIT';
export const PACKAGENAME_INIT_SUCCESS = 'PACKAGENAME_INIT_SUCCESS';
export const PACKAGENAME_INIT_ERROR = 'PACKAGENAME_INIT_ERROR';

export const MENULIST_INIT = 'MENULIST_INIT';
export const MENULIST_INIT_SUCCESS = 'MENULIST_INIT_SUCCESS';
export const MENULIST_INIT_ERROR = 'MENULIST_INIT_ERROR';

export const FILTERLIST_INIT = 'FILTERLIST_INIT';
export const FILTERLIST_INIT_SUCCESS = 'FILTERLIST_INIT_SUCCESS';
export const FILTERLIST_INIT_ERROR = 'FILTERLIST_INIT_ERROR';

export const CHANNEL_LIST_INIT = 'CHANNEL_LIST_INIT';
export const CHANNEL_LIST_INIT_SUCCESS = 'CHANNEL_LIST_INIT_SUCCESS';
export const CHANNEL_LIST_INIT_ERROR = 'CHANNEL_LIST_INIT_ERROR';

export const COUNTRY_LIST_INIT = 'COUNTRY_LIST_INIT';
export const COUNTRY_LIST_INIT_SUCCESS = 'COUNTRY_LIST_INIT_SUCCESS';
export const COUNTRY_LIST_INIT_ERROR = 'COUNTRY_LIST_INIT_ERROR';
//
export const CATEGORY_LIST_INIT = 'CATEGORY_LIST_INIT';
export const CATEGORY_LIST_INIT_SUCCESS = 'CATEGORY_LIST_INIT_SUCCESS';
export const CATEGORY_LIST_INIT_ERROR = 'CATEGORY_LIST_INIT_ERROR';
//
export const BRAND_LIST_INIT = 'BRAND_LIST_INIT';
export const BRAND_LIST_INIT_SUCCESS = 'BRAND_LIST_INIT_SUCCESS';
export const BRAND_LIST_INIT_ERROR = 'BRAND_LIST_INIT_ERROR';
//
export const PRIORITY_LIST_INIT = 'PRIORITY_LIST_INIT';
export const PRIORITY_LIST_INIT_SUCCESS = 'PRIORITY_LIST_INIT_SUCCESS';
export const PRIORITY_LIST_INIT_ERROR = 'PRIORITY_LIST_INIT_ERROR';
//
export const PUBLISHER_LIST_INIT = 'PUBLISHER_LIST_INIT';
export const PUBLISHER_LIST_INIT_SUCCESS = 'PUBLISHER_LIST_INIT_SUCCESS';
export const PUBLISHER_LIST_INIT_ERROR = 'PUBLISHER_LIST_INIT_ERROR';
//
export const STATUS_LIST_INIT = 'STATUS_LIST_INIT';
export const STATUS_LIST_INIT_SUCCESS = 'STATUS_LIST_INIT_SUCCESS';
export const STATUS_LIST_INIT_ERROR = 'STATUS_LIST_INIT_ERROR';
//

export const SET_GLOBAL_PACKAGE_NAME = 'SET_GLOBAL_PACKAGE_NAME';
export const SET_GLOBAL_REFRESH_RENDERING = 'SET_GLOBAL_REFRESH_RENDERING';