export const TOTAL_INCIDENTS = 'TOTAL_INCIDENTS';
export const TOTAL_INCIDENTS_SUCCESS = 'TOTAL_INCIDENTS_SUCCESS';
export const TOTAL_INCIDENTS_ERROR = 'TOTAL_INCIDENTS_ERROR';

export const INCIDENT_VOLUMES = 'INCIDENT_VOLUMES';
export const INCIDENT_VOLUMES_SUCCESS = 'INCIDENT_VOLUMES_SUCCESS';
export const INCIDENT_VOLUMES_ERROR = 'INCIDENT_VOLUMES_ERROR';

export const ACTIVECASE_CHANNEL = 'ACTIVECASE_CHANNEL';
export const ACTIVECASE_CHANNEL_SUCCESS = 'ACTIVECASE_CHANNEL_SUCCESS';
export const ACTIVECASE_CHANNEL_ERROR = 'ACTIVECASE_CHANNEL_ERROR';

export const DASHBOARD_DATA = 'DASHBOARD_DATA';
export const DASHBOARD_DATA_SUCCESS = 'DASHBOARD_DATA_SUCCESS';

export const SUBCHANNEL_INIT = 'SUBCHANNEL_INIT';
export const SUBCHANNEL_SUCCESS = 'SUBCHANNEL_SUCCESS';
export const SUBCHANNEL_ERROR = 'SUBCHANNEL_ERROR';

export const TOPTEN_LOCATION_INIT = 'TOPTEN_LOCATION_INIT';
export const TOPTEN_LOCATION_SUCCESS = 'TOPTEN_LOCATION_SUCCESS';
export const TOPTEN_LOCATION_ERROR = 'TOPTEN_LOCATION_ERROR';

export const CATEGORY_LEVEL_COUNT = 'CATEGORY_LEVEL_COUNT';
export const CATEGORY_LEVEL_COUNT_SUCCESS = 'CATEGORY_LEVEL_COUNT_SUCCESS';
export const CATEGORY_LEVEL_COUNT_ERROR = 'CATEGORY_LEVEL_COUNT_ERROR';

export const PUBLISHER_LEVEL_COUNT = 'PUBLISHER_LEVEL_COUNT';
export const PUBLISHER_LEVEL_COUNT_SUCCESS = 'PUBLISHER_LEVEL_COUNT_SUCCESS';
export const PUBLISHER_LEVEL_COUNT_ERROR = 'PUBLISHER_LEVEL_COUNT_ERROR';

export const SET_SIDE_DRAWER = 'SET_SIDE_DRAWER';