export const DOWNLOAD_INIT = 'DOWNLOAD_INIT';
export const DOWNLOAD_INIT_SUCCESS = 'DOWNLOAD_INIT_SUCCESS';
export const DOWNLOAD_INIT_ERROR = 'DOWNLOAD_INIT_ERROR';
export const DOWNLOAD_INIT_CLEAR = 'DOWNLOAD_INIT_CLEAR';