export const PUBLISHER_ADD =  'PUBLISHER_ADD'
export const PUBLISHER_ADD_SUCCESS = 'PUBLISHER_ADD_SUCCESS'
export const PUBLISHER_ADD_ERROR = 'PUBLISHER_ADD_ERROR'
export const PUBLISHER_ADD_CLEAR = 'PUBLISHER_ADD_CLEAR'

export const PUBLISHER_GET =  'PUBLISHER_GET'
export const PUBLISHER_GET_SUCCESS = 'PUBLISHER_GET_SUCCESS'
export const PUBLISHER_GET_ERROR = 'PUBLISHER_GET_ERROR'
export const PUBLISHER_GET_CLEAR = 'PUBLISHER_GET_CLEAR'

export const PUBLISHER_UPDATE =  'PUBLISHER_UPDATE'
export const PUBLISHER_UPDATE_SUCCESS = 'PUBLISHER_UPDATE_SUCCESS'
export const PUBLISHER_UPDATE_ERROR = 'PUBLISHER_UPDATE_ERROR'
export const PUBLISHER_UPDATE_CLEAR = 'PUBLISHER_UPDATE_CLEAR'


export const PUBLISHER_DELETE =  'PUBLISHER_DELETE'
export const PUBLISHER_DELETE_SUCCESS = 'PUBLISHER_DELETE_SUCCESS'
export const PUBLISHER_DELETE_ERROR = 'PUBLISHER_DELETE_ERROR'
export const PUBLISHER_DELETE_CLEAR = 'PUBLISHER_DELETE_CLEAR'