export const THREESIXTY_INIT = 'THREESIXTY_INIT';
export const THREESIXTY_FETCH_SUCCESS = 'THREESIXTY_FETCH_SUCCESS';
export const THREESIXTY_FETCH_ERROR = 'THREESIXTY_FETCH_ERROR';

export const THREESIXTY_UPLOAD_INIT = 'THREESIXTY_UPLOAD_INIT';
export const THREESIXTY_UPLOAD_SUCCESS = 'THREESIXTY_UPLOAD_SUCCESS';
export const THREESIXTY_UPLOAD_ERROR = 'THREESIXTY_UPLOAD_ERROR';
