export const TICKET_INCIDENTS = 'TICKET_INCIDENTS';
export const TICKET_INCIDENTS_SUCCESS = 'TICKET_INCIDENTS_SUCCESS';
export const TICKET_INCIDENTS_ERROR = 'TICKET_INCIDENTS_ERROR';

export const TICKETSEARCH_INCIDENTS = 'TICKETSEARCH_INCIDENTS';
export const TICKETSEARCH_INCIDENTS_SUCCESS = 'TICKETSEARCH_INCIDENTS_SUCCESS';
export const TICKETSEARCH_INCIDENTS_ERROR = 'TICKETSEARCH_INCIDENTS_ERROR';

export const TICKETPRIORITY_INCIDENTS = 'TICKETPRIORITY_INCIDENTS';
export const TICKETPRIORITY_INCIDENTS_SUCCESS = 'TICKETPRIORITY_INCIDENTS_SUCCESS';
export const TICKETPRIORITY_INCIDENTS_ERROR = 'TICKETPRIORITY_INCIDENTS_ERROR';

export const TICKETASSIGNEE_INCIDENTS = 'TICKETASSIGNEE_INCIDENTS';
export const TICKETASSIGNEE_INCIDENTS_SUCCESS = 'TICKETASSIGNEE_INCIDENTS_SUCCESS';
export const TICKETASSIGNEE_INCIDENTS_ERROR = 'TICKETASSIGNEE_INCIDENTS_ERROR';

export const TICKETSTATUS_INCIDENTS = 'TICKETSTATUS_INCIDENTS';
export const TICKETSTATUS_INCIDENTS_SUCCESS = 'TTICKETSTATUS_INCIDENTS_SUCCESS';
export const TICKETSTATUS_INCIDENTS_ERROR = 'TICKETSTATUS_INCIDENTS_ERROR';

export const TICKET_UPDATE_INIT = 'TICKET_UPDATE_INIT';
export const TICKET_UPDATE_SUCCESS = 'TTICKET_UPDATE_SUCCESS';
export const TICKET_UPDATE_ERROR = 'TICKET_UPDATE_ERROR';


