export const VERIFICATION_INIT = 'VERIFICATION_INIT';
export const VERIFICATION_FETCH = 'VERIFICATION_FETCH';
export const VERIFICATION_FETCH_SUCCESS = 'VERIFICATION_FETCH_SUCCESS';
export const VERIFICATION_FETCH_ERROR = 'VERIFICATION_FETCH_ERROR';

export const BULK_BANK_VERIFICATION_INIT = 'BULK_VERIFICATION_INIT';
export const BULK_BANK_VERIFICATION_FETCH = 'BULK_VERIFICATION_FETCH';
export const BULK_BANK_VERIFICATION_FETCH_SUCCESS =
  'BULK_VERIFICATION_FETCH_SUCCESS';
export const BULK_BANK_VERIFICATION_FETCH_ERROR =
  'BULK_VERIFICATION_FETCH_ERROR';
